name: Test Friday Gemini

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-friday:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Friday Gemini test
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: node friday_gemini.js
